export const  contactdetail=[
    {profile:"/person.jpg",id:"1",phonenon:"4145645",des:"dsfushdfnjsndfks",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"2",phonenon:"5454",des:"idfjiosjf",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"3",phonenon:"748451",des:"idfhiosdfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"4",phonenon:"7451",des:"ijdfiosj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"5",phonenon:"784561",des:"dfjnsiodfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"6",phonenon:"74651",des:"ifjiosjd",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"7",phonenon:"748451",des:"idfhiosdfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"8",phonenon:"7451",des:"ijdfiosj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"9",phonenon:"784561",des:"dfjnsiodfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"10",phonenon:"74651",des:"ifjimd fosjd",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"11",phonenon:"748451",des:"idff hiosdfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"12",phonenon:"7451",des:"ijdfio sj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"13",phonenon:"784561",des:"dfjnsdf siodfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"14",phonenon:"74651",des:"ifjiosdf sjd",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"15",phonenon:"748451",des:"idfhsdf iosdfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"16",phonenon:"7451",des:"ijdfiosdf sj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"17",phonenon:"784561",des:"dfjnsdf siodfj",send:"receve",time:"12:15 AM"},
    {profile:"/person.jpg",id:"18",phonenon:"74651",des:"ifjiosdf sjd",send:"receve",time:"12:15 AM"},
]
const Chatdata=[
    {id:"1",chatid:"1",data:"first",send:"receve",time:"12:10",seen:"seen"},
    {id:"1",chatid:"2",data:"hello1",send:"receve",time:"12:10",seen:"seen"},
    {id:"1",chatid:"3",data:"hello2",send:"send",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"4",data:"hello3",send:"send",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"5",data:"hello1",send:"receve",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"7",data:"hello2",send:"send",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"8",data:"hello3",send:"receve",time:"12:10",seen:"seen"},
    {id:"1",chatid:"9",data:"hello1",send:"receve",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"10",data:"hello",send:"send",time:"12:10",seen:"seen"},
    {id:"1",chatid:"11",data:"hello2",send:"receve",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"12",data:"hello3",send:"send",time:"12:10",seen:"seen"},
    {id:"1",chatid:"13",data:"hello1",send:"receve",time:"12:10",seen:"unseen"},
    {id:"1",chatid:"14",data:"helloufhiuds",send:"receve",time:"12:10",seen:"seen"},
    {id:"1",chatid:"15",data:"hello2",send:"send",time:"12:10",seen:"unseen"},-
    {id:"1",chatid:"16",data:"last",send:"receve",time:"12:10",seen:"seen"},
    {id:"5",chatid:"17",data:"hello1",send:"receve",time:"12:10",seen:"unseen"},
    {id:"5",chatid:"18",data:"hello",send:"receve",time:"12:10",seen:"seen"},
    {id:"5",chatid:"19",data:"hello2",send:"receve",time:"12:10",seen:"unseen"},
    {id:"5",chatid:"20",data:"hello3",send:"receve",time:"12:10",seen:"seen"},
    {id:"6",chatid:"21",data:"hello1",send:"receve",time:"12:10",seen:"unseen"},
    {id:"6",chatid:"22",data:"hello",send:"receve",time:"12:10",seen:"seen"},
    {id:"6",chatid:"23",data:"hello2",send:"receve",time:"12:10",seen:"unseen"},
    {id:"6",chatid:"24",data:"hello3",send:"receve",time:"12:10",seen:"seen"},
    {id:"7",chatid:"25",data:"hello1",send:"receve",time:"12:10",seen:"unseen"},
    {id:"7",chatid:"26",data:"hello",send:"receve",time:"12:10",seen:"seen"},
    {id:"7",chatid:"27",data:"hello2",send:"receve",time:"12:10",seen:"unseen"},
    {id:"7",chatid:"28",data:"hello3",send:"receve",time:"12:10",seen:"seen"},
]
export const chatdata=Chatdata.reverse();